version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${PORT:-6379}:6379"
    volumes:
      - ./data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
